export const enum PosFunctions {
    ExtTest = 1,
    ExtKillPrev = 2,
    ExtCompleteOrder = 3,
    ExtOpenOrder = 4,
    ExtTenderOrder = 5,
    ExtVoidOrder = 6,
    ExtLitemdefFromPos = 7,
    ExtLitemdefFromFile = 8,
    ExtHelpUse = 9,
    ExtGetVers = 10,
    ExtGetCapabilities = 11,
    ExtIntOffline = 12,
    ExtGetBussinessDay = 13,
    ExtOpenDay = 14,
    ExtCloseDay = 15,
    ExtRetryOrders = 16,
    ExtRestartPos = 18,
    ExtGetItemInfo = 21,
    ExtGetMenuInfo = 22,
    ExtTestDiag = 30,
    ExtGetOpenTables = 31,
    ExtUnlockOrder = 32,
    ExtSimphonyOrder = 33,
}
